CREATE TABLE country (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  name VARCHAR(128) NOT NULL
);

CREATE TABLE region (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  country_id BIGINT NOT NULL,
  name VARCHAR(128) NOT NULL,
  FOREING KEY (country_id) REFERENCES country (id)
);

CREATE TABLE city (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  region_id BIGINT NOT NULL,
  name VARCHAR(128) NOT NULL,
  FOREING KEY (region_id) REFERENCES region (id)
);

